### ISSUE TITLE
Add type annotations

### ISSUE THREAD

**Issue by hackebrot** [hackebrot/pytest-md#9]
We already have mypy enabled in tox - now we only need type annotations for our plugin code 😀

**Comment by ssd71** [comment]
I would like to work on this, where do I start?

**Comment by hackebrot** [comment]
Hi @ssd71! 👋 

You can information on  type annotations in the [Python documentation][docs]. I suggest starting with the methods of the [MarkdownPlugin class](https://github.com/hackebrot/pytest-md/blob/master/src/pytest_md/plugin.py#L19) Make sure to check for type errors when adding annotations with `tox -e mypy`.

Alternatively you can try out [MonkeyType](https://github.com/Instagram/MonkeyType) and see if it works for **pytest-md**.

Thank you for looking into this! 📝 

[docs]: https://docs.python.org/3/library/typing.html
